-- 0010_cashflow_sale_lock.sql
-- Prevent manual edits/deletes of cash_flow rows that were generated by a sale.

CREATE OR REPLACE FUNCTION block_sale_cashflow_edit() RETURNS trigger AS $$
BEGIN
  IF OLD.sale_id IS NOT NULL AND current_setting('app.bypass_check', true) IS DISTINCT FROM 'rpc' THEN
    RAISE EXCEPTION 'No se puede modificar cash_flow generado por venta. Editá la venta directamente.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION block_sale_cashflow_delete() RETURNS trigger AS $$
BEGIN
  IF OLD.sale_id IS NOT NULL AND current_setting('app.bypass_check', true) IS DISTINCT FROM 'rpc' THEN
    RAISE EXCEPTION 'No se puede eliminar cash_flow generado por venta. Eliminá la venta directamente.';
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS cash_flow_lock_sale_update ON cash_flow;
CREATE TRIGGER cash_flow_lock_sale_update
  BEFORE UPDATE ON cash_flow
  FOR EACH ROW EXECUTE FUNCTION block_sale_cashflow_edit();

DROP TRIGGER IF EXISTS cash_flow_lock_sale_delete ON cash_flow;
CREATE TRIGGER cash_flow_lock_sale_delete
  BEFORE DELETE ON cash_flow
  FOR EACH ROW EXECUTE FUNCTION block_sale_cashflow_delete();
